import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import { writeFileSync } from "fs"

/*
 * generateFirebaseSwConfig — Vite plugin that writes public/firebase-sw-config.js
 * at build/dev startup.
 *
 * Service workers live in /public and are NOT processed by Vite, so VITE_ env vars
 * cannot be injected into them via import.meta.env. This plugin reads the VITE_FIREBASE_*
 * vars from the resolved Vite env and writes them as a plain JS assignment
 *   self.FIREBASE_SW_CONFIG = { ... }
 * so that firebase-messaging-sw.js can importScripts('/firebase-sw-config.js') and
 * initialise Firebase synchronously on first evaluation — satisfying the browser's
 * requirement that push/pushsubscriptionchange handlers be registered at that time.
 *
 * The generated file is gitignored (.gitignore already excludes public/firebase-sw-config.js)
 * because it contains project credentials. CI/CD sets the VITE_FIREBASE_* secrets and
 * the plugin regenerates the file on every build.
 */
function generateFirebaseSwConfig() {
  return {
    name: "generate-firebase-sw-config",
    configResolved(config) {
      const env = config.env // all VITE_ vars resolved for the current mode
      const cfg = {
        apiKey:            env.VITE_FIREBASE_API_KEY            || "",
        authDomain:        env.VITE_FIREBASE_AUTH_DOMAIN        || "",
        projectId:         env.VITE_FIREBASE_PROJECT_ID         || "",
        storageBucket:     env.VITE_FIREBASE_STORAGE_BUCKET     || "",
        messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
        appId:             env.VITE_FIREBASE_APP_ID             || "",
      }
      writeFileSync(
        "public/firebase-sw-config.js",
        `/* Auto-generated by vite.config.js — do not edit */\nself.FIREBASE_SW_CONFIG = ${JSON.stringify(cfg, null, 2)};\n`,
        "utf8",
      )
    },
  }
}

/*
 * vite.config.js — Vite build and dev-server configuration for ConnectHub frontend.
 *
 * WHAT IS VITE?
 *   Vite is a build tool and development server for modern JavaScript apps.
 *   It serves files with native ES Modules during development (blazing fast —
 *   no bundling step), and uses Rollup to produce an optimised bundle for production.
 *
 * SECTIONS IN THIS CONFIG:
 *   plugins  — adds the React plugin which handles JSX → JS transformation and
 *              React Fast Refresh (hot-reload that preserves component state).
 *   server   — dev server settings (port, proxy).
 *   test     — Vitest unit test configuration (separate from Playwright E2E tests).
 *
 * PROXY EXPLAINED:
 *   During local development the frontend runs at http://localhost:5173 and the
 *   API Gateway runs at http://localhost:8080. The proxy rewrites requests so
 *   that fetch("/api/auth/login") is transparently forwarded to
 *   http://localhost:8080/api/auth/login without triggering browser CORS errors.
 *   In production (Vercel), these are handled differently via environment variables.
 *
 * UNIT TESTS (Vitest):
 *   npm run test:unit          → runs all *.test.js files once and exits
 *   npm run test:unit:watch    → re-runs on file changes (great during development)
 *   npm run test:unit:coverage → produces a coverage report in ./coverage/
 *
 *   Vitest is configured to use jsdom as the test environment, which simulates a
 *   browser (window, document, localStorage, etc.) without launching a real browser.
 *   This is perfect for testing utility functions, stores, and pure logic.
 *   For full end-to-end UI tests use Playwright (npm run test).
 */
export default defineConfig({
  plugins: [react(), generateFirebaseSwConfig()],
  server: {
    port: 5173,
    strictPort: true,
    proxy: {
      "/api": {
        target: "http://localhost:8080",
        changeOrigin: true,
      },
      "/ws": {
        target: "http://localhost:8080",
        ws: true,
        changeOrigin: true,
      },
      "/oauth2/authorization": {
        target: "http://localhost:8080",
        changeOrigin: true,
      },
      "/login/oauth2": {
        target: "http://localhost:8080",
        changeOrigin: true,
      },
    },
  },

  build: {
    // Raise the chunk-size warning threshold — our vendor chunks are intentionally larger
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      output: {
        /*
         * Manual chunk splitting — keeps vendor libraries in separate, long-cached
         * files so a code change in your app does not bust the React/STOMP/date-fns cache.
         */
        manualChunks: {
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-stomp': ['@stomp/stompjs', 'sockjs-client'],
          'vendor-ui': ['lucide-react', 'date-fns', 'emoji-picker-react'],
        },
      },
    },
  },

  /*
   * test — Vitest configuration block.
   *
   * environment: "jsdom"
   *   Vitest runs in Node.js by default, which has no window/document/fetch.
   *   jsdom provides a simulated browser environment so tests that reference
   *   window.dispatchEvent, window.fetch, localStorage, etc. work correctly.
   *
   * globals: true
   *   Makes test(), describe(), expect(), vi, etc. available globally without
   *   needing to import them in every test file (same ergonomics as Jest).
   *
   * setupFiles
   *   A list of files that run once before the test suite starts.
   *   src/test/setup.js is where you put global mocks and polyfills
   *   (e.g., mocking matchMedia for components that use it).
   *
   * coverage
   *   provider: "v8" uses Node's built-in V8 coverage for speed.
   *   reporter: generates text output in the terminal + an HTML report.
   *   exclude: we skip coverage for node_modules, test files themselves,
   *            vite config, and Playwright E2E tests.
   */
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["src/test/setup.js"],
    // Only pick up Vitest unit tests — exclude Playwright E2E specs
    include: ["src/**/*.test.{js,jsx,ts,tsx}"],
    exclude: ["node_modules/**", "tests/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      exclude: [
        "node_modules/**",
        "**/*.test.{js,jsx,ts,tsx}",
        "vite.config.js",
        "playwright.config.js",
        "tests/**",
        "src/test/**",
        // React UI components — behaviour is covered by Playwright E2E tests
        "src/components/**",
        // React hook: requires renderHook from @testing-library/react (not installed)
        "src/hooks/**",
        // Browser-only / SDK-dependent services excluded from unit coverage.
        // api.js relies on token-refresh machinery that needs integration testing;
        // firebase.js and websocket.js require real browser APIs (ServiceWorker, STOMP).
        "src/services/firebase.js",
        "src/services/websocket.js",
        "src/services/api.js",
        // React theme context — no unit-testable business logic
        "src/theme/**",
        // App entry points — tested end-to-end by Playwright smoke suite
        "src/App.jsx",
        "src/main.jsx",
        // Service worker lives in /public — not processed by Vite
        "public/**",
      ],
    },
  },
})
